### PR TITLE
 Vectorization of the <for loop> on Chebychev polynomial degrees

### PR DESCRIPTION
**Pull request by K-H-Ismail**
* Getting rid of the ugly for loop on the Chebychev polynomial degrees
* Formatting and linting the file

### CODE REVIEW

**Comment by iiisak** [comment]
Great find! I'll be closing my pull request

**Comment by K-H-Ismail** [comment]
Thanks ! You actually did the whole job !

**Comment by iiisak** [comment]
Just tested it and this change makes ChebyKAN ~11x faster

**Comment by SynodicMonth** [comment]
Thats indeed a giant boost! Really appreciate that! 
I'll reserve the unvectorized one in another file for a quick and brief understanding.

**Comment by K-H-Ismail** [comment]
Many thanks to you for helping demystify KANs,
Many thanks to @iiisak for thinking about the trigonometric formulation
Actually, the formula extends for all x in R that way:
image
or simply this one
image


We could implement this and get rid of the tanh in the beginning.

I'm afraid this will add nothing. As far as I understood from your discussion with @JanRocketMan [Issue:3](https://github.com/SynodicMonth/ChebyKAN/issues/3#issuecomment-2104534051), all polynomial interpolations that could be used yield a form of LANs or GLUs.

Using a B-spline as in the original paper is just using a piece-wise polynomial interpolation that has nicer properties instead.

What do you think about this?

**Comment by SynodicMonth** [comment]
> Many thanks to you for helping demystify KANs, Many thanks to @iiisak for thinking about the trigonometric formulation Actually, the formula extends for all x in R that way: image or simply this one image
> 
> We could implement this and get rid of the tanh in the beginning.
> 
> I'm afraid this will add nothing. As far as I understood from your discussion with @JanRocketMan [Issue:3](https://github.com/SynodicMonth/ChebyKAN/issues/3#issuecomment-2104534051), all polynomial interpolations that could be used yield a form of LANs or GLUs.
> 
> Using a B-spline as in the original paper is just using a piece-wise polynomial interpolation that has nicer properties instead.
> 
> What do you think about this?

Sorry for the late reply, ive been dealing with a fever.

I definitely agree. We've find some major advantages of B-splines (actually drawbacks of chebyKAN) in the discussion:
B-spline is less equal (though in theory its expandable) to LAN 
B-spilne is capable of continual learning (#8)
B-spline is also more universal (not 100% sure)

In my opinion:
yeah B-spline is also just a nicer interpolation. But its good enough in some specific problems.
I see people have find many ways to accelerate the original KAN. KAN might be a great tool in those problems. But its too early to replace every MLP with KAN. i havn't see its advantage in larger problems like CV/NLP.

**Comment by K-H-Ismail** [comment]
@SynodicMonth 
Yes indeed, thank you for your insights.

**Comment by yuedajiong** [comment]
I have read through your discussion and code. I have a question: you use cos(n * acos(x)) to replace the iteration of T_n(x). We know that trigonometric functions like sin and cos internally use approximation methods such as Taylor expansion, which essentially involve loops and piecewise processing. Why is the acos + cos approach faster?

**Comment by yuedajiong** [comment]
"B-spilne is capable of continual learning"

I just believe that different approximation methods have different advantages. In fact, for high-frequency trigonometric functions, like sin(999x), there are very few methods that can approximate them quickly (using the raw algorithm(+,x,...no approximation), without defining it a priori as sin(exp(THETA_learnable)*x))

**Comment by yuedajiong** [comment]
I read a paper 'A note on computing with Kolmogorov Superpositions without iterations'   (David Sprecher @UCSB @2021)

‘without iterations’, it sounds impressive! the network should be wider.

**Comment by K-H-Ismail** [comment]
Hello,

Regarding the cos implementation. You could go for a polynomial Taylor expansion. Given that one can implement it fastly, there will be no difference in time.

Regarding Sprecher's work. We have been looking at that in detail these last few months. Sprecher's inner functions are fractal and cause some issues for differentiable learning. However, we are investigating some encouraging avenues.   Depending on the result, We might share some of our preliminary work in a preprint.

**Comment by yuedajiong** [comment]
great!   @K-H-Ismail

**Pull request merged**
